"""ReportLab rendering of the Applicant Repayment Assessment PDF.

Applicant-facing structure (spec section 18): Your Repayment Score, Your
Application Information, Credit History Verification, Your Financial
Indicators, Your Digital & Behavioral Indicators, What Supported Your Score,
What Reduced Your Score, How the Final Score Was Generated.

All interpretation content comes from the shared interpretation utilities
(build_interpretation_blocks) — the same blocks the dashboard shows, so the
PDF and the UI can never disagree. Raw model internals (contribution values)
are never printed: applicants see values, meanings and direction statements.
"""

from datetime import datetime
from xml.sax.saxutils import escape

from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable, KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table,
    TableStyle,
)

from interpretation import build_interpretation_blocks

CATEGORY_COLORS = {
    "Very Low": colors.HexColor("#b71c1c"),
    "Low": colors.HexColor("#e65100"),
    "Moderate": colors.HexColor("#f9a825"),
    "High": colors.HexColor("#2e7d32"),
    "Very High": colors.HexColor("#1b5e20"),
}

NAVY = colors.HexColor("#1a3a5c")
GRAY = colors.HexColor("#6b7280")
LIGHT_ROW = colors.HexColor("#f3f6f9")
BORDER = colors.HexColor("#d5dbe1")

NEUTRAL_SCORE_NOTE = (
    "This score represents the model's estimated repayment assessment based on "
    "the information provided and patterns learned during training."
)
DISCLAIMER = (
    "This score is a model-estimated repayment assessment and is not a "
    "guaranteed probability of repayment or an automatic loan approval "
    "decision. This report is generated by an AI-based prototype using a "
    "synthetic dataset. The repayment score is an estimated model output and "
    "does not guarantee loan approval, repayment, or financial outcome. "
    "Real-world deployment would require validation using representative "
    "real-world data, appropriate governance, and regulatory and fairness "
    "assessment."
)

_TITLE = ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=19,
                        textColor=NAVY, spaceAfter=2)
_SUBTITLE = ParagraphStyle("Subtitle", fontName="Helvetica", fontSize=8.5,
                           textColor=GRAY, leading=11)
_H2 = ParagraphStyle("H2", fontName="Helvetica-Bold", fontSize=12.5,
                     textColor=NAVY, spaceBefore=14, spaceAfter=6)
_H3 = ParagraphStyle("H3", fontName="Helvetica-Bold", fontSize=10,
                     textColor=colors.HexColor("#374151"), spaceBefore=8, spaceAfter=3)
_BODY = ParagraphStyle("Body", fontName="Helvetica", fontSize=9.5,
                       leading=13.5, textColor=colors.HexColor("#111827"))
_VALUE = ParagraphStyle("Value", fontName="Helvetica-Bold", fontSize=10,
                        leading=13, textColor=colors.HexColor("#111827"))
_SCORE = ParagraphStyle("Score", fontName="Helvetica-Bold", fontSize=24, leading=27)
_CATEGORY = ParagraphStyle("Category", fontName="Helvetica-Bold", fontSize=13,
                           leading=16, textColor=GRAY)
_SMALL = ParagraphStyle("Small", fontName="Helvetica", fontSize=8, leading=10.5,
                        textColor=GRAY)
_SMALL_ITALIC = ParagraphStyle("SmallItalic", fontName="Helvetica-Oblique",
                               fontSize=8, leading=10.5, textColor=GRAY)
_TABLE_LABEL = ParagraphStyle("TableLabel", fontName="Helvetica", fontSize=8.5,
                              textColor=GRAY)
_TABLE_VALUE = ParagraphStyle("TableValue", fontName="Helvetica-Bold", fontSize=9.5,
                              textColor=colors.HexColor("#111827"))
_TABLE_SMALL = ParagraphStyle("TableSmall", fontName="Helvetica", fontSize=8,
                              leading=10, textColor=colors.HexColor("#111827"))

_ROW_STYLE = TableStyle([
    ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_ROW]),
    ("LINEBELOW", (0, 0), (-1, -1), 0.5, BORDER),
    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
])


def unique_report_path(reports_dir):
    """repayment_assessment_<timestamp>.pdf, suffixed on same-second collisions."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = reports_dir / f"repayment_assessment_{stamp}.pdf"
    counter = 1
    while path.exists():
        counter += 1
        path = reports_dir / f"repayment_assessment_{stamp}_{counter}.pdf"
    return path


def _score_gauge(score, category):
    width, height = 440, 42
    gauge = Drawing(width, height)
    track_x, track_w, track_h, track_y = 10, width - 20, 13, 16
    gauge.add(Rect(track_x, track_y, track_w, track_h,
                   fillColor=colors.HexColor("#e5e7eb"), strokeColor=None))
    fill_w = max(track_w * min(max(score, 0.0), 100.0) / 100.0, 2.0)
    gauge.add(Rect(track_x, track_y, fill_w, track_h,
                   fillColor=CATEGORY_COLORS[category], strokeColor=None))
    gauge.add(String(track_x, 4, "0", fontName="Helvetica", fontSize=7.5, fillColor=GRAY))
    gauge.add(String(track_x + track_w - 14, 4, "100",
                     fontName="Helvetica", fontSize=7.5, fillColor=GRAY))
    return gauge


def _score_section(assessment):
    score = assessment["repayment_score"]
    category = assessment["score_category"]
    color = CATEGORY_COLORS[category]

    score_para = Paragraph(f"{score:.1f} / 100", ParagraphStyle(
        "ScoreColored", parent=_SCORE, textColor=color))
    category_para = Paragraph(
        f"Assessment: {category}", ParagraphStyle("CatColored", parent=_CATEGORY,
                                                  textColor=color))
    header = Table([[score_para, category_para]], colWidths=[290, 197])
    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))

    return [
        header,
        Spacer(1, 4),
        _score_gauge(score, category),
        Spacer(1, 10),
        Paragraph(escape(assessment.get("_summary") or NEUTRAL_SCORE_NOTE), _SMALL),
    ]


def _info_table(blocks):
    """Label/value pairs in two columns — the applicant's own information."""
    rows = []
    for i in range(0, len(blocks), 2):
        left = blocks[i]
        right = blocks[i + 1] if i + 1 < len(blocks) else None
        rows.append([
            Paragraph(left["label"], _TABLE_LABEL),
            Paragraph(left["value"], _TABLE_VALUE),
            Paragraph(right["label"] if right else "", _TABLE_LABEL),
            Paragraph(right["value"] if right else "", _TABLE_VALUE),
        ])
    table = Table(rows, colWidths=[129, 114.5, 129, 114.5])
    table.setStyle(_ROW_STYLE)
    return table


def _value_line(block):
    value = block["value"]
    if block.get("band"):
        return Paragraph(escape(f"{value} \u2014 {block['band']}"), _VALUE)
    return Paragraph(escape(value), _VALUE)


def _credit_section(interp, assessment):
    story = []
    credit = interp.get("credit_history")
    if credit:
        story.append(Paragraph(
            escape(f"Verified result: {credit['derived_loan_history']}"), _VALUE))
        story.append(Paragraph("How this was determined:", _SMALL))
        rows = [[Paragraph("Indicator", _TABLE_LABEL),
                 Paragraph("Value", _TABLE_LABEL)]]
        rows.extend(
            [Paragraph(escape(row["label"]), _TABLE_SMALL),
             Paragraph(escape(row["value"]), _TABLE_SMALL)]
            for row in credit["explanation"]["rows"]
        )
        table = Table(rows, colWidths=[200, 287])
        table.setStyle(_ROW_STYLE)
        story.append(table)
        story.append(Spacer(1, 5))
        story.append(Paragraph(escape(credit["explanation"]["narrative"]), _BODY))
        if credit.get("inconsistent"):
            story.append(Paragraph(
                "Note: some credit-information indicators in this record are "
                "contradictory; please review them with your loan officer.",
                _SMALL_ITALIC))
        story.append(Spacer(1, 3))
        story.append(Paragraph(escape(credit["demo_notice"]), _SMALL_ITALIC))
    else:
        # CLI/demo path: the category was supplied with the applicant data
        value = next(
            (f["value"] for f in assessment["applicant_features"]
             if f["feature"] == "Credit History"), "")
        story.append(Paragraph(escape(value), _VALUE))
        story.append(Paragraph(
            "This classification was provided with the applicant data for "
            "this report.", _SMALL))
    return story


def _components_table(block):
    rows = [[Paragraph("Component", _TABLE_LABEL),
             Paragraph("Weight", _TABLE_LABEL),
             Paragraph("Score", _TABLE_LABEL),
             Paragraph("What it measures", _TABLE_LABEL)]]
    for component in block["components"]:
        rows.append([
            Paragraph(escape(component["name"]), _TABLE_SMALL),
            Paragraph(escape(component["weight"]), _TABLE_SMALL),
            Paragraph(escape(f"{component['score']:.1f}"), _TABLE_SMALL),
            Paragraph(escape(component["description"]), _TABLE_SMALL),
        ])
    table = Table(rows, colWidths=[105, 40, 38, 304])
    table.setStyle(_ROW_STYLE)
    return table


def _indicator_block(block):
    """One feature/indicator: heading, value, meaning, how-calculated."""
    story = [
        Paragraph(escape(block["label"]), _H3),
        _value_line(block),
    ]
    if block.get("meaning"):
        story.append(Paragraph(escape(block["meaning"]), _BODY))
    if block.get("components"):
        story.append(Spacer(1, 3))
        story.append(Paragraph("How is this calculated?", _SMALL))
        story.append(Paragraph(escape(block["formula"]), _TABLE_SMALL))
        story.append(Spacer(1, 2))
        story.append(_components_table(block))
        story.append(Spacer(1, 3))
        story.append(Paragraph(escape(block["simulation_note"]), _SMALL_ITALIC))
    elif block.get("how_calculated"):
        story.append(Paragraph(
            "How is this calculated? " + escape(block["how_calculated"]),
            _SMALL_ITALIC))
    if block.get("reference_note"):
        story.append(Paragraph(escape(block["reference_note"]), _SMALL))
    story.append(Spacer(1, 4))
    # keep the heading with at least its value line
    return [KeepTogether(story[:2])] + story[2:]


def _contributors_section(title, blocks, empty_text):
    story = [Paragraph(title, _H2)]
    if not blocks:
        story.append(Paragraph(empty_text, _BODY))
        return story
    for block in blocks:
        story.append(KeepTogether([
            Paragraph(escape(f"{block['feature']} \u2014 {block['value']}"), _H3),
            Paragraph(escape(block["meaning"]), _BODY),
        ]))
        story.append(Paragraph(escape(block["influence"]), _BODY))
        if block.get("reference_note"):
            story.append(Paragraph(escape(block["reference_note"]), _SMALL))
        story.append(Spacer(1, 4))
    return story


def _pipeline_section(interp, explanation):
    story = [Paragraph("How the Final Score Was Generated", _H2)]
    rows = []
    for stage in interp["score_pipeline"]:
        rows.append([
            Paragraph(escape(stage["name"]), _TABLE_VALUE),
            Paragraph(escape(stage["description"]), _TABLE_SMALL),
        ])
    rows.append([
        Paragraph("ML Scoring Model", ParagraphStyle(
            "PipelineModel", parent=_TABLE_VALUE, textColor=NAVY)),
        Paragraph("considers all inputs together", _TABLE_SMALL),
    ])
    rows.append([
        Paragraph("Repayment Score", ParagraphStyle(
            "PipelineScore", parent=_TABLE_VALUE, textColor=NAVY)),
        Paragraph("the model's estimated assessment", _TABLE_SMALL),
    ])
    table = Table(rows, colWidths=[160, 327])
    table.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -2), [colors.white, LIGHT_ROW]),
        ("BACKGROUND", (0, -2), (-1, -1), LIGHT_ROW),
        ("BOX", (0, -2), (-1, -1), 0.5, BORDER),
        ("LINEBELOW", (0, 0), (-1, -3), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(table)
    story.append(Spacer(1, 4))
    story.append(Paragraph(escape(interp["pipeline_note"]), _SMALL))
    story.append(Spacer(1, 8))
    story.append(Paragraph(escape(explanation["overall_explanation"]), _BODY))
    return story


def _build_story(assessment, explanation):
    # one shared interpretation source for the PDF and the dashboard; the
    # CLI path (no stored blocks yet) builds them on the fly
    interp = assessment.get("interpretation") or build_interpretation_blocks(
        assessment.get("feature_values", {}), assessment)
    assessment = {**assessment, "_summary": explanation["summary"]}

    timestamp = datetime.now().strftime("%d %b %Y, %H:%M")
    story = [
        Paragraph("Applicant Repayment Assessment", _TITLE),
        Paragraph(
            "AI Credit Scoring Prototype \u00b7 Alternative-Data Model "
            "\u00b7 Trained on Synthetic Data",
            _SUBTITLE,
        ),
        Paragraph(f"Generated: {timestamp}", _SUBTITLE),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1.1, color=NAVY),
        Spacer(1, 10),

        Paragraph("Your Repayment Score", _H2),
    ]
    story.extend(_score_section(assessment))

    story.append(Paragraph("Your Application Information", _H2))
    story.append(_info_table(interp["application_info"]))

    story.append(Paragraph("Credit History Verification", _H2))
    story.extend(_credit_section(interp, assessment))

    story.append(Paragraph("Your Financial Indicators", _H2))
    for block in interp["financial_indicators"]:
        story.extend(_indicator_block(block))

    story.append(Paragraph("Your Digital & Behavioral Indicators", _H2))
    for block in interp["digital_indicators"]:
        story.extend(_indicator_block(block))

    story.extend(_contributors_section(
        "What Supported Your Score", interp["top_supported"],
        "No features meaningfully increased the score for this application."))
    story.extend(_contributors_section(
        "What Reduced Your Score", interp["top_reduced"],
        "No features meaningfully reduced the score for this application."))

    story.extend(_pipeline_section(interp, explanation))

    story.append(Paragraph("Important Notice", _H2))
    disclaimer = Table([[Paragraph(DISCLAIMER, _SMALL_ITALIC)]],
                       colWidths=[487])
    disclaimer.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_ROW),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 9),
        ("RIGHTPADDING", (0, 0), (-1, -1), 9),
    ]))
    story.append(disclaimer)
    return story


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GRAY)
    canvas.drawString(54, 32, "AI prototype \u2014 synthetic data \u00b7 not financial advice")
    canvas.drawRightString(A4[0] - 54, 32, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def render_report(assessment, explanation, output_path):
    """Render the assessment + explanation into a professional PDF."""
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=54, rightMargin=54, topMargin=52, bottomMargin=56,
        title="Applicant Repayment Assessment",
        author="AI Credit Scoring Prototype",
        subject="Model-estimated repayment score with applicant-facing explanations",
    )
    doc.build(_build_story(assessment, explanation),
              onFirstPage=_footer, onLaterPages=_footer)
    return output_path
