"""ReportLab rendering of the Applicant Repayment Assessment PDF."""

import io
import textwrap
from datetime import datetime
from xml.sax.saxutils import escape

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    HRFlowable, Image, KeepTogether, Paragraph, SimpleDocTemplate, Spacer,
    Table, TableStyle,
)

CATEGORY_COLORS = {
    "Very Low": colors.HexColor("#b71c1c"),
    "Low": colors.HexColor("#e65100"),
    "Moderate": colors.HexColor("#f9a825"),
    "High": colors.HexColor("#2e7d32"),
    "Very High": colors.HexColor("#1b5e20"),
}

NAVY = colors.HexColor("#1a3a5c")
GRAY = colors.HexColor("#6b7280")
LIGHT_ROW = colors.HexColor("#f3f6f9")
BORDER = colors.HexColor("#d5dbe1")

NEUTRAL_SCORE_NOTE = (
    "This score represents the model's estimated repayment assessment based on "
    "the information provided and patterns learned during training."
)
DISCLAIMER = (
    "This score is a model-estimated repayment assessment and is not a "
    "guaranteed probability of repayment or an automatic loan approval "
    "decision. This report is generated by an AI-based prototype using a "
    "synthetic dataset. The repayment score is an estimated model output and "
    "does not guarantee loan approval, repayment, or financial outcome. "
    "Real-world deployment would require validation using representative "
    "real-world data, appropriate governance, and regulatory and fairness "
    "assessment."
)

_TITLE = ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=19,
                        textColor=NAVY, spaceAfter=2)
_SUBTITLE = ParagraphStyle("Subtitle", fontName="Helvetica", fontSize=8.5,
                           textColor=GRAY, leading=11)
_H2 = ParagraphStyle("H2", fontName="Helvetica-Bold", fontSize=12.5,
                     textColor=NAVY, spaceBefore=14, spaceAfter=6)
_H3 = ParagraphStyle("H3", fontName="Helvetica-Bold", fontSize=10,
                     textColor=colors.HexColor("#374151"), spaceBefore=8, spaceAfter=3)
_BODY = ParagraphStyle("Body", fontName="Helvetica", fontSize=9.5,
                       leading=13.5, textColor=colors.HexColor("#111827"))
_BULLET = ParagraphStyle("Bullet", fontName="Helvetica", fontSize=9.5, leading=13.5,
                         textColor=colors.HexColor("#111827"),
                         leftIndent=14, bulletIndent=4, spaceAfter=2)
_SCORE = ParagraphStyle("Score", fontName="Helvetica-Bold", fontSize=24, leading=27)
_CATEGORY = ParagraphStyle("Category", fontName="Helvetica-Bold", fontSize=13,
                           leading=16, textColor=GRAY)
_SMALL = ParagraphStyle("Small", fontName="Helvetica", fontSize=8, leading=10.5,
                        textColor=GRAY)
_SMALL_ITALIC = ParagraphStyle("SmallItalic", fontName="Helvetica-Oblique",
                               fontSize=8, leading=10.5, textColor=GRAY)
_TABLE_LABEL = ParagraphStyle("TableLabel", fontName="Helvetica", fontSize=8.5,
                              textColor=GRAY)
_TABLE_VALUE = ParagraphStyle("TableValue", fontName="Helvetica-Bold", fontSize=9.5,
                              textColor=colors.HexColor("#111827"))


def unique_report_path(reports_dir):
    """repayment_assessment_<timestamp>.pdf, suffixed on same-second collisions."""
    reports_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = reports_dir / f"repayment_assessment_{stamp}.pdf"
    counter = 1
    while path.exists():
        counter += 1
        path = reports_dir / f"repayment_assessment_{stamp}_{counter}.pdf"
    return path


def _score_gauge(score, category):
    width, height = 440, 42
    gauge = Drawing(width, height)
    track_x, track_w, track_h, track_y = 10, width - 20, 13, 16
    gauge.add(Rect(track_x, track_y, track_w, track_h,
                   fillColor=colors.HexColor("#e5e7eb"), strokeColor=None))
    fill_w = max(track_w * min(max(score, 0.0), 100.0) / 100.0, 2.0)
    gauge.add(Rect(track_x, track_y, fill_w, track_h,
                   fillColor=CATEGORY_COLORS[category], strokeColor=None))
    gauge.add(String(track_x, 4, "0", fontName="Helvetica", fontSize=7.5, fillColor=GRAY))
    gauge.add(String(track_x + track_w - 14, 4, "100",
                     fontName="Helvetica", fontSize=7.5, fillColor=GRAY))
    return gauge


def _contribution_chart(assessment):
    """Horizontal bar chart of the strongest actual contributions."""
    ranked = assessment["all_contributions"]  # sorted, most positive first
    positives = [c for c in ranked if c["shap_value"] > 0][:3]
    negatives = [c for c in reversed(ranked) if c["shap_value"] < 0][:3]
    bars = sorted(positives + negatives, key=lambda c: c["shap_value"])

    labels = [textwrap.fill(f"{c['feature']} ({c['value']})", 38) for c in bars]
    values = [c["shap_value"] for c in bars]

    fig, ax = plt.subplots(figsize=(7.4, 0.62 * len(bars) + 1.0))
    bar_colors = ["#2e7d32" if v > 0 else "#c62828" for v in values]
    ax.barh(range(len(bars)), values, color=bar_colors, height=0.62)
    ax.set_yticks(range(len(bars)), labels, fontsize=9)
    ax.axvline(0, color="#374151", lw=0.9)

    limit = max(abs(v) for v in values) * 1.28
    ax.set_xlim(-limit, limit)
    for i, v in enumerate(values):
        ax.text(v + (0.06 * limit if v >= 0 else -0.06 * limit), i,
                f"{v:+.1f}", va="center",
                ha="left" if v >= 0 else "right", fontsize=9, color="#111827")
    ax.set_xlabel("Contribution to the model's repayment score (points)", fontsize=9)
    ax.tick_params(axis="x", labelsize=8)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.grid(axis="x", alpha=0.25)

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def _applicant_table(assessment):
    features = assessment["applicant_features"]
    rows = []
    for i in range(0, len(features), 2):
        left = features[i]
        right = features[i + 1] if i + 1 < len(features) else None
        rows.append([
            Paragraph(left["feature"], _TABLE_LABEL),
            Paragraph(left["value"], _TABLE_VALUE),
            Paragraph(right["feature"] if right else "", _TABLE_LABEL),
            Paragraph(right["value"] if right else "", _TABLE_VALUE),
        ])

    table = Table(rows, colWidths=[129, 114.5, 129, 114.5])
    table.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_ROW]),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return table


def _score_section(assessment):
    score = assessment["repayment_score"]
    category = assessment["score_category"]
    color = CATEGORY_COLORS[category]

    score_para = Paragraph(f"{score:.1f} / 100", ParagraphStyle(
        "ScoreColored", parent=_SCORE, textColor=color))
    category_para = Paragraph(
        f"Assessment: {category}", ParagraphStyle("CatColored", parent=_CATEGORY,
                                                  textColor=color))
    header = Table([[score_para, category_para]], colWidths=[290, 197])
    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))

    return [
        header,
        Spacer(1, 4),
        _score_gauge(score, category),
        Spacer(1, 10),
        Paragraph(NEUTRAL_SCORE_NOTE, _SMALL),
    ]


def _factors_section(assessment, explanation):
    story = []
    positives = explanation["positive_factors"]
    negatives = explanation["negative_factors"]

    story.append(Paragraph("Positive Factors", _H3))
    if positives:
        # LLM wording is free text: escape it so ReportLab's markup parser
        # can never choke on tag-like sequences (e.g. "income <br> stable")
        story.extend(
            Paragraph(escape(f), _BULLET, bulletText="\u2022") for f in positives)
    else:
        story.append(Paragraph("No features meaningfully increased the score for "
                               "this application.", _BODY))

    story.append(Paragraph("Factors Reducing the Score", _H3))
    if negatives:
        story.extend(
            Paragraph(escape(f), _BULLET, bulletText="\u2022") for f in negatives)
    else:
        story.append(Paragraph("No features meaningfully reduced the score for "
                               "this application.", _BODY))

    story.append(Paragraph("Overall Explanation", _H3))
    story.append(Paragraph(escape(explanation["overall_explanation"]), _BODY))
    story.append(Spacer(1, 6))
    story.append(Paragraph(escape(explanation["summary"]), _BODY))
    return story


def _chart_section(assessment):
    buf = _contribution_chart(assessment)
    image_reader = ImageReader(buf)
    img_w, img_h = image_reader.getSize()
    display_w = 6.55 * inch
    display_h = display_w * img_h / img_w
    buf.seek(0)

    return [
        Image(buf, width=display_w, height=display_h),
        Spacer(1, 3),
        Paragraph(
            "Each bar shows how strongly a feature moved the model's score for this "
            "applicant, relative to the average training profile. Green raised the "
            "score, red lowered it.",
            _SMALL_ITALIC,
        ),
    ]


def _build_story(assessment, explanation):
    timestamp = datetime.now().strftime("%d %b %Y, %H:%M")
    story = [
        Paragraph("Applicant Repayment Assessment", _TITLE),
        Paragraph(
            "AI Credit Scoring Prototype \u00b7 Alternative-Data Model "
            "\u00b7 Trained on Synthetic Data",
            _SUBTITLE,
        ),
        Paragraph(f"Generated: {timestamp}", _SUBTITLE),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1.1, color=NAVY),
        Spacer(1, 10),

        Paragraph("Repayment Assessment", _H2),
    ]
    story.extend(_score_section(assessment))

    story.append(Paragraph("Applicant Information", _H2))
    story.append(_applicant_table(assessment))

    story.append(Paragraph("Why This Score Was Generated", _H2))
    story.extend(_factors_section(assessment, explanation))

    chart_block = [Paragraph("Feature Contribution Analysis", _H2)]
    chart_block.extend(_chart_section(assessment))
    story.append(KeepTogether(chart_block))

    story.append(Paragraph("Important Notice", _H2))
    disclaimer = Table([[Paragraph(DISCLAIMER, _SMALL_ITALIC)]],
                       colWidths=[487])
    disclaimer.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_ROW),
        ("BOX", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 9),
        ("RIGHTPADDING", (0, 0), (-1, -1), 9),
    ]))
    story.append(disclaimer)
    return story


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(GRAY)
    canvas.drawString(54, 32, "AI prototype \u2014 synthetic data \u00b7 not financial advice")
    canvas.drawRightString(A4[0] - 54, 32, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def render_report(assessment, explanation, output_path):
    """Render the assessment + explanation into a professional PDF."""
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=54, rightMargin=54, topMargin=52, bottomMargin=56,
        title="Applicant Repayment Assessment",
        author="AI Credit Scoring Prototype",
        subject="Model-estimated repayment score with feature contribution analysis",
    )
    doc.build(_build_story(assessment, explanation),
              onFirstPage=_footer, onLaterPages=_footer)
    return output_path
